### ISSUE TITLE
Checkout starlight

### ISSUE THREAD

**Issue by natefinch** [qri-io/starlib#12]
https://github.com/starlight-go/starlight - it lets you easily dump functions and values from go into starlight without writing a lot of boilerplate.

It is in its infancy, but might be a good way to save some time.

**Comment by b5** [comment]
Hey @natefinch! Thanks so much for pointing us to starlight. For us at Qri starlight isn't the right fit, but your project looks great, and anyone interested in a starlark standard library would benefit from knowing about starlight IMHO. Do you have any interest in adding a related projects section to each of our readme's, or better yet, an `examples` directory in each project that demos use of each other's work?

**Comment by b5** [comment]
closing due to age.
