### ISSUE TITLE
html parser - make more like beautifulsoup/more pythonic?

### ISSUE THREAD

**Issue by osterbit** [qri-io/starlib#25]
top things
- in python a single functions often allow a wide variety of ordered arguments or keyword arguments  each of which may also vary in type
   - I think this pattern could be followed without any need for additional functionality by just adding a couple wrapper functions containing type switches
    - a few examples (and more in the pasted text below):
```python
soup.find_all("li") # <li></li> elements
soup.find_all(name="li") # same as above
soup.find_all(attrs=["class"]) #elements with a class attribute
# elements with a specific class and an id matching a certain pattern
soup.find_all(attrs={"class": "warning", "id":re.compile("item\-\d+")})
# elements specified using their name as the keyword
soup.find_all(href="https://qri.io")
```

some related notes pasted from previous pr comment:

- beautifulsoup supports both its default syntax via `soup.find()` and `soup.find_all()` and jquery/css selector syntax via `soup.select()` so if we made some syntax update, the current `Find` function could just be renamed `Select`
- I don't think we would want to try to do something that's halfway between bs4 and jquery (as it might alienate both sides) but here are some of the top syntatic details that would make a bs4 user feel more at home:
    - having a `Find()` method that returns a single node and a `FindAll()` method that returns a list of nodes
    - returning a list of values for a multi-value attribute
    - allowing the find methods to take a variety of arguments (rather than being in separate functions)--for example in bs4 the following are all valid (*i think*)
      - passing the tag name (already supported)
        -`soup.find_all("a")`
      - passing a list of tags
        -`soup.find_all(["a", "li"])`
      - passing a function (like Filter): 
        -`soup.find_all(lambda tag: tag.has_attr('class') and not tag.has_attr('id'))`
      - passing keyword args where the value can be a string, regex, or function:
        -`soup.find_all(href=re.compile("^col-\w\w-\d+"))`
        -`soup.find_all(class_=some_func)`

**Comment by b5** [comment]
Now that #26 is merged, we're well on our way to beautifulsoup-style html wrangling!
