### ISSUE TITLE
starlark repo/package rename has occurred

### ISSUE THREAD

**Issue by jakebailey** [qri-io/starlib#8]
It looks like the big skylark -> starlark rename has occurred, with the new repo [here](https://github.com/google/starlark-go), and a new import path of `go.starlark.net/starlark`.

I'm sure this will end up affecting all of your repos, but I figured I'd pick this one to let you know. Happy renaming! 🙂

**Comment by dustmop** [comment]
Done! Thanks for the heads up, @jakebailey!
